#!/usr/bin/env node
// Derives www/ (the bundle the native iOS and Android shells ship) from static/.
//
// The browser app at /vocare keeps loading React and @babel/standalone from a
// CDN and transpiling vocare-app.jsx at runtime. The native shells cannot: they
// must work with no network at all, and paying 2.8MB plus a second of on-device
// transpile at every cold start is exactly the first impression we are trying to
// fix. So this script rewrites the CDN references to vendored copies, transpiles
// the JSX ahead of time with esbuild, and injects the absolute API base the
// bundle needs now that it no longer shares an origin with the backend.
//
// www/ is generated output. Never hand-edit it — change static/ and re-run.
// `--check` rebuilds into a temp dir and diffs, so CI can catch drift.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const STATIC = path.join(ROOT, 'static');
const CHECK = process.argv.includes('--check');

// The backend the native bundle talks to. Override with VOCARE_API_BASE when
// building against a different deployment.
const API_BASE =
  process.env.VOCARE_API_BASE ||
  'https://vocare-grc-bot.yellowtree-d62e92d2.australiaeast.azurecontainerapps.io';

// Ad configuration. AdMob unit ids are publishable, not secrets — they are
// designed to ship inside the app binary. They are still read from the
// environment so a fork or a test build does not inherit ours, and an unset id
// simply means no banner rather than a crash.
//
// There is nothing here for purchases: StoreKit and Play Billing authenticate
// through the signed app itself, so the client needs no key at all. The only
// credentials involved are the server's, and those never reach the bundle.
const ADMOB_IOS_BANNER = process.env.VOCARE_ADMOB_IOS_BANNER || '';
const ADMOB_ANDROID_BANNER = process.env.VOCARE_ADMOB_ANDROID_BANNER || '';
// Google requires test ads during development; shipping live ids in a debug
// build is a policy violation, so this defaults on unless explicitly released.
const ADS_TEST = process.env.VOCARE_ADS_TEST !== 'false';

const GENERATED = 'GENERATED by scripts/build-www.mjs — do not edit. Source: static/';

function buildInto(outDir) {
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(path.join(outDir, 'vendor'), { recursive: true });

  // ── index.html ───────────────────────────────────────────────────────────
  let html = fs.readFileSync(path.join(STATIC, 'vocare.html'), 'utf8');

  // React/ReactDOM: CDN development builds → vendored production builds.
  html = html.replace(
    /<script src="https:\/\/unpkg\.com\/react@[\d.]+\/umd\/react\.development\.js"[^>]*><\/script>/,
    '<script src="./vendor/react.production.min.js"></script>',
  );
  html = html.replace(
    /<script src="https:\/\/unpkg\.com\/react-dom@[\d.]+\/umd\/react-dom\.development\.js"[^>]*><\/script>/,
    '<script src="./vendor/react-dom.production.min.js"></script>',
  );

  // Babel is compile-time here, so the runtime copy goes away entirely.
  html = html.replace(
    /\s*<script src="https:\/\/unpkg\.com\/@babel\/standalone@[\d.]+\/babel\.min\.js"[^>]*><\/script>/,
    '',
  );

  // Google Fonts (preconnects + stylesheet) → one vendored stylesheet.
  html = html.replace(
    /\s*<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com"[^>]*\/>/g,
    '',
  );
  html = html.replace(
    /\s*<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com"[^>]*\/>/g,
    '',
  );
  html = html.replace(
    /<link href="https:\/\/fonts\.googleapis\.com\/css2[^"]*" rel="stylesheet"\s*\/>/,
    '<link href="./vendor/fonts.css" rel="stylesheet" />',
  );

  // The runtime-transpiled source → the pre-built bundle, preceded by the
  // config the bundle needs to find the backend and know it is running native.
  const bootstrap =
    '<script>\n'
    + `  window.VOCARE_API_BASE = ${JSON.stringify(API_BASE)};\n`
    + '  window.VOCARE_NATIVE_BUNDLE = true;\n'
    + `  window.VOCARE_ADMOB_IOS_BANNER = ${JSON.stringify(ADMOB_IOS_BANNER)};\n`
    + `  window.VOCARE_ADMOB_ANDROID_BANNER = ${JSON.stringify(ADMOB_ANDROID_BANNER)};\n`
    + `  window.VOCARE_ADS_TEST = ${JSON.stringify(ADS_TEST)};\n`
    + '</script>\n'
    + '<script src="./app.js"></script>';
  html = html.replace(
    /<script type="text\/babel" src="\/static\/vocare-app\.jsx"><\/script>/,
    bootstrap,
  );

  assertRewritten(html);
  html = html.replace('<head>', `<head>\n<!-- ${GENERATED}vocare.html -->`);
  fs.writeFileSync(path.join(outDir, 'index.html'), html);

  // ── app.js ───────────────────────────────────────────────────────────────
  // vocare-app.jsx has no imports and uses React/ReactDOM as globals, so
  // esbuild acts as a pure JSX transpiler here: output stays ~1:1 with the
  // source and is trivially reviewable.
  const esbuild = path.join(ROOT, 'node_modules', '.bin', 'esbuild');
  execFileSync(
    esbuild,
    [
      path.join(STATIC, 'vocare-app.jsx'),
      '--loader:.jsx=jsx',
      '--target=es2019',
      '--format=iife',
      `--outfile=${path.join(outDir, 'app.js')}`,
      `--banner:js=// ${GENERATED}vocare-app.jsx`,
    ],
    { stdio: 'inherit' },
  );

  // ── vendored runtime ─────────────────────────────────────────────────────
  copyDep(outDir, 'react', 'umd/react.production.min.js', 'react.production.min.js');
  copyDep(outDir, 'react-dom', 'umd/react-dom.production.min.js', 'react-dom.production.min.js');

  // Fonts are committed under static/vendor-fonts/ rather than fetched, so a
  // build never depends on the network. Noto Sans SC is deliberately absent:
  // the full CJK face is 8-10MB, and the stack in vocare-app.jsx falls through
  // to PingFang SC on iOS and Noto Sans CJK on Android, both system-resident.
  const fontsSrc = path.join(STATIC, 'vendor-fonts');
  if (fs.existsSync(fontsSrc)) {
    fs.cpSync(fontsSrc, path.join(outDir, 'vendor'), { recursive: true });
  } else {
    console.warn(
      '[build-www] static/vendor-fonts/ is missing — the bundle will fall back\n'
      + '            to system fonts. Run scripts/fetch-fonts.sh to vendor them.',
    );
    fs.writeFileSync(
      path.join(outDir, 'vendor', 'fonts.css'),
      '/* Placeholder: run scripts/fetch-fonts.sh to vendor the webfonts. */\n',
    );
  }

  // ── demo assets ──────────────────────────────────────────────────────────
  const demoSrc = path.join(STATIC, 'demo');
  if (fs.existsSync(demoSrc)) {
    fs.cpSync(demoSrc, path.join(outDir, 'demo'), { recursive: true });
  }
}

function copyDep(outDir, pkg, relSrc, destName) {
  const src = path.join(ROOT, 'node_modules', pkg, relSrc);
  if (!fs.existsSync(src)) {
    throw new Error(`Missing ${pkg} build at ${src}. Run: npm install`);
  }
  fs.copyFileSync(src, path.join(outDir, 'vendor', destName));
}

// A silently-failed regex would ship a bundle that still reaches for the CDN —
// offline that is a blank screen, and it would pass every other check. Fail loudly.
function assertRewritten(html) {
  const leaks = [
    ['unpkg.com', 'a CDN script tag'],
    ['fonts.googleapis.com', 'a Google Fonts stylesheet'],
    ['fonts.gstatic.com', 'a Google Fonts preconnect'],
    ['text/babel', 'a runtime-transpiled script tag'],
    ['/static/vocare-app.jsx', 'the un-bundled source reference'],
  ];
  const found = leaks.filter(([needle]) => html.includes(needle));
  if (found.length) {
    throw new Error(
      'build-www: rewrite failed, output still contains:\n'
      + found.map(([n, what]) => `  - ${n} (${what})`).join('\n')
      + '\nThe markup in static/vocare.html probably changed shape. Fix the '
      + 'replacements in scripts/build-www.mjs.',
    );
  }
}

function diffDirs(a, b) {
  const walk = (dir, base = '') =>
    fs.readdirSync(dir, { withFileTypes: true }).flatMap(e =>
      e.isDirectory()
        ? walk(path.join(dir, e.name), path.join(base, e.name))
        : [path.join(base, e.name)],
    );
  if (!fs.existsSync(b)) return ['www/ does not exist'];
  const [fa, fb] = [walk(a).sort(), walk(b).sort()];
  const problems = [];
  for (const f of new Set([...fa, ...fb])) {
    if (!fa.includes(f)) problems.push(`unexpected: www/${f}`);
    else if (!fb.includes(f)) problems.push(`missing: www/${f}`);
    else if (!fs.readFileSync(path.join(a, f)).equals(fs.readFileSync(path.join(b, f)))) {
      problems.push(`differs: www/${f}`);
    }
  }
  return problems;
}

const target = CHECK
  ? fs.mkdtempSync(path.join(os.tmpdir(), 'vocare-www-'))
  : path.join(ROOT, 'www');

buildInto(target);

if (CHECK) {
  const problems = diffDirs(target, path.join(ROOT, 'www'));
  fs.rmSync(target, { recursive: true, force: true });
  if (problems.length) {
    console.error(
      'www/ is out of date with static/. Run `npm run build:www` and commit the result.\n'
      + problems.map(p => `  ${p}`).join('\n'),
    );
    process.exit(1);
  }
  console.log('www/ is up to date with static/.');
} else {
  console.log(`Built www/ from static/ (API base: ${API_BASE})`);
}
